using UnityEngine;
using System.Collections;

public class DeathZone : MonoBehaviour {
    public AutoGeneratedCurves path;

    void OnTriggerEnter(Collider other)
    {
        if (other.gameObject == path.balleRigidBody.gameObject)
            path.Respawn();
    }
}
